name: CI
on:
  push:
  workflow_call:
    inputs:
      reviewdog_args:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: make dependencies

      - name: Build
        run: make build

  reviewdog:
    name: Reviewdog
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install lint tools
        run: make install-tools

      - name: Set Reviewdog args
        id: reviewdog
        run: |
          if [ -z "${{ inputs.reviewdog_args }}" ]; then
            echo "::set-output name=args::-reporter=github-check"
          else
            echo "::set-output name=args::${{ inputs.reviewdog_args }}"
          fi

      - name: Run reviewdog
        run: make reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWDOG_ARGS: ${{ steps.reviewdog.outputs.args }}

  test:
    name: Test
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: make dependencies

      - name: Test
        run: make test

