name: release

on:
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      reviewdog_args: '-diff="git diff master"'
  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: confirm cache
        run: echo "cache is ${{ steps.cache.outputs.cache-hit }}"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
